repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest before push
        entry: pytest
        language: system
        pass_filenames: false
        stages: [pre-push]